services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./otterwiki/app-data:/app-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otterwiki.rule=Host(`wiki.fabricant.ucsd.edu`)"
      - "traefik.http.routers.otterwiki.entrypoints=websecure"
      - "traefik.http.routers.otterwiki.tls.certresolver=letsencrypt"
      - "traefik.http.routers.otterwiki.middlewares=authentik@docker"
