services:
  grafana:
    image: grafana/grafana-enterprise:12.3
    container_name: grafana
    user: '1000'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=e4eadmin
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_e4eadmin_password
    secrets:
      - grafana_e4eadmin_password
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
      - ./grafana:/etc/grafana:ro
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`dashboard.waiter.ucsd.edu`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention.time=2y --storage.tsdb.retention.size=700GB --storage.tsdb.wal-compression
    restart: unless-stopped
    networks:
      - prometheus_network
      - default
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - ./prometheus-data:/prometheus:rw

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.28.0
    container_name: blackbox_exporter
    volumes:
      - ./blackbox-exporter:/config:ro
    command: --config.file=/config/blackbox.yml
    ports:
      - 9115:9115
    dns: 8.8.8.8secrets:

grafana_e4eadmin_password:
  file: .secrets/gf_admin_password.txt
networks:
  prometheus_network:
    external: true