
  
services:
  postgres_label_studio:
    image: postgres:16.4
    container_name: postgres_label_studio
    restart: always
    shm_size: 128 mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin_password
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/:rw
      - ./postgres/config/:/etc/postgresql/:ro
      - ./postgres/scripts/:/docker-entrypoint-initdb.d/:ro
      - /etc/passwd:/etc/passwd:ro
    secrets:
      - postgres_admin_password
    command: --config_file=/etc/postgresql/postgres.conf
    ports:
      - 5433:5432
    networks:
      - label_studio
    user: "${USER_ID}:${GROUP_ID}"

  label_studio_pg:
    container_name: label-studio
    image: heartexlabs/label-studio:1.20.0
    restart: unless-stopped
    depends_on:
      - postgres_label_studio
    networks:
      - label_studio
      - caddy_proxy
    volumes:
      - ./label_studio_data_pg:/label-studio/data
      - /share/label-studio/files:/data
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/data
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=e4e@ucsd.edu
      - LABEL_STUDIO_HOST=https://labeler.e4e.ucsd.edu
      - CSRF_TRUSTED_ORIGINS=https://labeler.e4e.ucsd.edu
      - DJANGO_DB=default
      - POSTGRE_NAME=label_studio
      - POSTGRE_USER=label_studio_pg
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=postgres_label_studio
    labels:
      caddy: labeler.e4e.ucsd.edu
      caddy.reverse_proxy: "{{upstreams 8080}}"
    env_file:
      - .secrets/label_studio_admin_password_pg.env
networks:
  label_studio: