- name: Add Docker GPG APT key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present
- name: Add docker-components
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

# The following updates the Docker Daemon File to fully take advantage of CUDA.
- name: Install Docker config
  become: true
  notify: Restart Docker
  ansible.builtin.copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0622' # user read/write, group read

- name: Get Docker GID
  command: /bin/bash ./scripts/get_docker_gid.sh
  register: docker_group_id

- name: Ensure group "docker-remap-docker" exists with correct gid
  become: true
  ansible.builtin.group:
    name: docker-remap-docker
    state: present
    gid: "{{ 100000 + docker_group_id | int }}"

- name: Grant group docker-remap-docker read access to a file
  become: true
  ansible.posix.acl:
    path: /var/run/docker.sock
    entity: docker-remap-docker
    etype: group
    permissions: rw
    state: present

- name: Get Fabricant Admin UID
  command: /usr/bin/id -u fabricant-admin
  register: fabricant_admin_id

- name: Add the user 'fabricant-admin-remap-docker'
  become: true
  ansible.builtin.user:
    name: fabricant-admin-remap-docker
    comment: Docker Remapped Fabricant Admin
    uid: "{{ 100000 + fabricant_admin_id.stdout | int  }}"
    groups: docker-remap-docker