- name: Install microk8s Snap Package
  become: true
  community.general.snap:
    name: microk8s
    state: present
    classic: true
- name: Add user 'fabricant-admin' to 'microk8s'
  become: yes
  user:
    name: fabricant-admin
    groups: microk8s
    append: yes
- name: Change kube folder ownership
  become: yes
  hosts: microk8s
  tasks:
    - file:
        path: /home/fabricant-admin/.kube
        owner: fabricant-admin
        group: fabricant-admin
        state: directory