- name: Install microk8s Snap Package
  become: true
  community.general.snap:
    name: microk8s
    state: present
    classic: true
- name: Add user 'fabricant-admin' to 'microk8s'
  become: true
  user:
    name: fabricant-admin
    groups: microk8s
    append: yes
- name: Recursively change ownership of ~/.kube to fabricant-admin
  become: true
  ansible.builtin.file:
    path: /home/fabricant-admin/.kube
    state: directory
    owner: fabricant-admin
    group: fabricant-admin
    recurse: yes

- name: Install microceph Snap Package
  become: true
  community.general.snap:
    name: microceph
    state: present

- name: Enable microk8s addons
  become: true
  ansible.builtin.command:
    cmd: microk8s enable dns dashboard registry rook-ceph

- name: Install helm Snap Package
  become: true
  community.general.snap:
    name: helm
    state: present
    classic: true
