- name: Configure auto-upgrades
  become: true
  ansible.builtin.copy:
    src: apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
- name: Configure unattended-upgrades
  become: true
  ansible.builtin.copy:
    src: apt.conf.d/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'